### ISSUE TITLE
.dat input file not recognized

### ISSUE THREAD

**Issue by rrpastro** [OxES/k2sc#14]
Would you please give some examples what type of parameters in ASCII file does k2sc support. 
I have a '.dat' file that has time, cadence, flux, flux error, xpos, ypos and quality. But I get the errror that this file is not supported. There is no where documented which explains how to use ASCII file how to save the parameters in ASCII file to make ready for running k2sc,

**Comment by rrpastro** [comment]
I figured out it is issue with python 3. The ASCII file is supported by py27 but not by python 3 in my mac. Even if I use python27 to run my ASCII file, I get the following error:
'''
File "/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 30, in _cholesky
    raise LinAlgError("%d-th leading minor not positive definite" % info)
numpy.linalg.linalg.LinAlgError: 4-th leading minor not positive definite
'''
when I choose default kernel. But if I choose 'basic' kernel, I don't get any error message.

**Comment by hpparvi** [comment]
Fixed the .dat-reading issue in Python 3 by changing the open mode from "rb" to "rt".
Still need to figure out the problem with the default kernel.
