### ISSUE TITLE
problem w. pyfits module in k2io.py

### ISSUE THREAD

**Issue by raesselstein** [OxES/k2sc#2]
I'm trying to run K2SC (latest version pulled this morning) on SPLOX multi-object LC format. I'm getting the error below. I think it could be something to do with the upgrade to using the astropy version of pyfits that was merged yesterday?

[resselstein@glamdring m67]$ k2sc C05_M67_detrendLC.fits -c 5 --splits 57177 --de-max-time 120 --de-npop 60 --save-dir red_real2 --logfile m67_new
Traceback (most recent call last):
  File "/users/resselstein/.local/bin/k2sc", line 41, in <module>
    from k2sc.k2io import select_reader, FITSWriter, SPLOXReader
  File "/users/resselstein/.local/lib/python2.7/site-packages/k2sc/k2io.py", line 37, in <module>
    pf_version = float(re.findall('^([0-9]\.[0-9])\.*', pf.__version__)[0])
AttributeError: 'module' object has no attribute '__version__'

**Comment by hpparvi** [comment]
Fixed.
