### ISSUE TITLE
standalone.py longer finds the keplerid

### ISSUE THREAD

**Issue by amcody** [OxES/k2sc#21]
We at Kepler have changed our lightkurve code such that what used to be keplerid is now targetid. That change needs to be propagated through to standalone.py. In particular, self.keplerid should now be self.targetid. Otherwise k2sc crashes. I would change it myself, but I am not sure if there are other places in the code that are similarly affected.

**Comment by benjaminpope** [comment]
Hi Ann Marie,

Thanks - I haven't kept up with the changing versions of lightkurve with
k2sc. Will fix asap - are you using it for anything? I have a couple of
other things in the next couple of days.

All the best,

Ben

On Wed, Feb 20, 2019 at 6:35 PM Ann Marie Cody <notifications@github.com>
wrote:

> We at Kepler have changed our lightkurve code such that what used to be
> keplerid is now targetid. That change needs to be propagated through to
> standalone.py. In particular, self.keplerid should now be self.targetid.
> Otherwise k2sc crashes. I would change it myself, but I am not sure if
> there are other places in the code that are similarly affected.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OxES_k2sc_issues_21&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=y2UVEGqREvbY8umXtGjDOJl0vFC2vnGgrD6fK_GSxVU&s=OKYV9zzTKt6Ia9tNkMzKwpM8hyjEh7cBQMfcbJJx3Z8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFvsFSUXQKOGzwG-2DLoRta6tZFhZCczzZks5vPdu9gaJpZM4bGVqI&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=y2UVEGqREvbY8umXtGjDOJl0vFC2vnGgrD6fK_GSxVU&s=0EguHXAXPSiaZQ3wsGMPQ7rMuED0xg6amoGCpqbiMHo&e=>
> .
>
-- 
Dr Benjamin Pope
NASA Sagan Fellow
Center for Cosmology and Particle Physics
New York University
726 Broadway
New York, NY 10003

**Comment by benjaminpope** [comment]
This is now fixed and I'm sorry I took so long!
