### ISSUE TITLE
sigma_clip returns three arrays

### ISSUE THREAD

**Issue by astrobatty** [OxES/k2sc#25]
Hi,

as I can see [sigma_clip](https://github.com/OxES/k2sc/blob/789610cd1c0fb1f90cfa1717da9920ad307b42f6/src/utils.py#L24) function has been updated and now if `separate_masks` is `True` it returns 3 arrays. However, in [standalone.py](https://github.com/OxES/k2sc/blob/789610cd1c0fb1f90cfa1717da9920ad307b42f6/src/standalone.py#L234) you only catch two of them, which raises an error. Changing `mlow, mhigh =` to `minf, mlow, mhigh =` in line 234 solves the issuse. Additionally `minf = isfinite(cflux)` in line 232 can be removed as it is calculated by the new `sigma_clip`.

Cheers,
astrobatty

**Comment by benjaminpope** [comment]
Thanks, well spotted! this is now resolved
